### PR TITLE
Introduce flash-message system

### PR DESCRIPTION
**Pull request by TRBRS**
## WHAT

Show message in Japanese

## WHY

Improve UX

### CODE REVIEW

**Comment by TRBRS** [comment]
https://i.gyazo.com/69b64668e08b4dde57d3dd9846238ca5.png

**Comment by TRBRS** [comment]
https://i.gyazo.com/ae82b13324c1a90d3ad035145515a5dc.png

**Comment by nekoze1210** [comment]
LGTM✨

**Comment by TRBRS** [comment]
ありがとうございます！

**Pull request merged**
